namespace: tina_pm
name: third_party
version: 1.2.0

authors:
  - Adeodato Simó

description: Third-party roles bundled as a collection
tags:
  - infrastructure

readme: README.md
license_file: LICENSE

repository: https://github.com/Tina-pm/tina_pm.third_party.git
